spring.application.name=api

spring.datasource.url=jdbc:oracle:thin:@techstoredb_tp?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=TechStore2024#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080